Repository techannihilation/TA_O, pull requests merged in 2018-08, with the labels that each got.

#1333 Nerf Anti Experimental Cannons
  units/corboucher.lua
  units/nebraska.lua
  units/tlldmc.lua
Labels: balance

#1355 Increase cost of final weapons again +30% metal and +30% energy cost
  units/armtabi.lua
  units/corflu.lua
  units/tllvanya.lua
Labels: balance

#1290 Update buildmenu for builderlvl3 lvl4
  units/abuilderlvl3.lua
  units/abuilderlvl4.lua
  units/armhcrus.lua
  units/cbuilderlvl3.lua
  units/cbuilderlvl4.lua
  units/corhcrus.lua
Labels: suggestion

#1288 Battle COM
  units/armmarv.lua
  units/corfred.lua
Labels: balance, suggestion
